---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: compliance-op-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            role: compliance
  template:
    metadata:
      name: '{{name}}-compliance-operator'
    spec:
      destination:
        namespace: openshift-compliance
        server: '{{server}}'
      project: default
      source:
        repoURL: 'https://github.com/taiseerhussein/gitops'
        path: common-base/openshift-compliance
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
