---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-cluster-management
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            demo: rhacm
        values:
          environment: nonprod
  template:
    metadata:
      name: '{{values.environment}}-hub-cluster'
    spec:
      destination:
        namespace: open-cluster-management
        server: '{{server}}'
      project: default
      source:
        path: common-base/open-cluster-management
        repoURL: https://github.com/taiseerhussein/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
